#ifndef OPCODE_H
#define OPCODE_H

#define ADC_IMMEDIATE        0x69
#define ADC_ZERO_PAGE        0x65
#define ADC_ZERO_PAGE_X      0x75
#define ADC_ABSOLUTE         0x6D
#define ADC_ABSOLUTE_X       0x7D
#define ADC_ABSOLUTE_Y       0x79
#define ADC_INDIRECT_X       0x61
#define ADC_INDIRECT_Y       0x71
#define AND_IMMEDIATE        0x29
#define AND_ZERO_PAGE        0x25
#define AND_ZERO_PAGE_X      0x35
#define AND_ABSOLUTE         0x2D
#define AND_ABSOLUTE_X       0x3D
#define AND_ABSOLUTE_Y       0x39
#define AND_INDIRECT_X       0x21
#define AND_INDIRECT_Y       0x31
#define ASL_ACCUMULATOR      0x0A
#define ASL_ZERO_PAGE        0x06
#define ASL_ZERO_PAGE_X      0x16
#define ASL_ABSOLUTE         0x0E
#define ASL_ABSOLUTE_X       0x1E
#define BCC_RELATIVE         0x90
#define BCS_RELATIVE         0xB0
#define BEQ_RELATIVE         0xF0
#define BIT_ZERO_PAGE        0x24
#define BIT_ABSOLUTE         0x2C
#define BMI_RELATIVE         0x30
#define BNE_RELATIVE         0xD0
#define BPL_RELATIVE         0x10
#define BRK_IMPLIED          0x00
#define BVC_RELATIVE         0x50
#define BVS_RELATIVE         0x70
#define CLC_IMPLIED          0x18
#define CLD_IMPLIED          0xD8
#define CLI_IMPLIED          0x58
#define CLV_IMPLIED          0xB8
#define CMP_IMMEDIATE        0xC9
#define CMP_ZERO_PAGE        0xC5
#define CMP_ZERO_PAGE_X      0xD5
#define CMP_ABSOLUTE         0xCD
#define CMP_ABSOLUTE_X       0xDD
#define CMP_ABSOLUTE_Y       0xD9
#define CMP_INDIRECT_X       0xC1
#define CMP_INDIRECT_Y       0xD1
#define CPX_IMMEDIATE        0xE0
#define CPX_ZERO_PAGE        0xE4
#define CPX_ABSOLUTE         0xEC
#define CPY_IMMEDIATE        0xC0
#define CPY_ZERO_PAGE        0xC4
#define CPY_ABSOLUTE         0xCC
#define DEC_ZERO_PAGE        0xC6
#define DEC_ZERO_PAGE_X      0xD6
#define DEC_ABSOLUTE         0xCE
#define DEC_ABSOLUTE_X       0xDE
#define DEX_IMPLIED          0xCA
#define DEY_IMPLIED          0x88
#define EOR_IMMEDIATE        0x49
#define EOR_ZERO_PAGE        0x45
#define EOR_ZERO_PAGE_X      0x55
#define EOR_ABSOLUTE         0x4D
#define EOR_ABSOLUTE_X       0x5D
#define EOR_ABSOLUTE_Y       0x59
#define EOR_INDIRECT_X       0x41
#define EOR_INDIRECT_Y       0x51
#define INC_ZERO_PAGE        0xE6
#define INC_ZERO_PAGE_X      0xF6
#define INC_ABSOLUTE         0xEE
#define INC_ABSOLUTE_X       0xFE
#define INX_IMPLIED          0xE8
#define INY_IMPLIED          0xC8
#define JMP_ABSOLUTE         0x4C
#define JMP_INDIRECT         0x6C
#define JSR_ABSOLUTE         0x20
#define LDA_IMMEDIATE        0xA9
#define LDA_ZERO_PAGE        0xA5
#define LDA_ZERO_PAGE_X      0xB5
#define LDA_ABSOLUTE         0xAD
#define LDA_ABSOLUTE_X       0xBD
#define LDA_ABSOLUTE_Y       0xB9
#define LDA_INDIRECT_X       0xA1
#define LDA_INDIRECT_Y       0xB1
#define LDX_IMMEDIATE        0xA2
#define LDX_ZERO_PAGE        0xA6
#define LDX_ZERO_PAGE_Y      0xB6
#define LDX_ABSOLUTE         0xAE
#define LDX_ABSOLUTE_Y       0xBE
#define LDY_IMMEDIATE        0xA0
#define LDY_ZERO_PAGE        0xA4
#define LDY_ZERO_PAGE_X      0xB4
#define LDY_ABSOLUTE         0xAC
#define LDY_ABSOLUTE_X       0xBC
#define LSR_ACCUMULATOR      0x4A
#define LSR_ZERO_PAGE        0x46
#define LSR_ZERO_PAGE_X      0x56
#define LSR_ABSOLUTE         0x4E
#define LSR_ABSOLUTE_X       0x5E
#define NOP_IMPLIED          0xEA
#define ORA_IMMEDIATE        0x09
#define ORA_ZERO_PAGE        0x05
#define ORA_ZERO_PAGE_X      0x15
#define ORA_ABSOLUTE         0x0D
#define ORA_ABSOLUTE_X       0x1D
#define ORA_ABSOLUTE_Y       0x19
#define ORA_INDIRECT_X       0x01
#define ORA_INDIRECT_Y       0x11
#define PHA_IMPLIED          0x48
#define PHP_IMPLIED          0x08
#define PLA_IMPLIED          0x68
#define PLP_IMPLIED          0x28
#define ROL_ACCUMULATOR      0x2A
#define ROL_ZERO_PAGE        0x26
#define ROL_ZERO_PAGE_X      0x36
#define ROL_ABSOLUTE         0x2E
#define ROL_ABSOLUTE_X       0x3E
#define ROR_ACCUMULATOR      0x6A
#define ROR_ZERO_PAGE        0x66
#define ROR_ZERO_PAGE_X      0x76
#define ROR_ABSOLUTE         0x6E
#define ROR_ABSOLUTE_X       0x7E
#define RTI_IMPLIED          0x40
#define RTS_IMPLIED          0x60
#define SBC_IMMEDIATE        0xE9
#define SBC_ZERO_PAGE        0xE5
#define SBC_ZERO_PAGE_X      0xF5
#define SBC_ABSOLUTE         0xED
#define SBC_ABSOLUTE_X       0xFD
#define SBC_ABSOLUTE_Y       0xF9
#define SBC_INDIRECT_X       0xE1
#define SBC_INDIRECT_Y       0xF1
#define SEC_IMPLIED          0x38
#define SED_IMPLIED          0xF8
#define SEI_IMPLIED          0x78
#define STA_ZERO_PAGE        0x85
#define STA_ZERO_PAGE_X      0x95
#define STA_ABSOLUTE         0x8D
#define STA_ABSOLUTE_X       0x9D
#define STA_ABSOLUTE_Y       0x99
#define STA_INDIRECT_X       0x81
#define STA_INDIRECT_Y       0x91
#define STX_ZERO_PAGE        0x86
#define STX_ZERO_PAGE_Y      0x96
#define STX_ABSOLUTE         0x8E
#define STY_ZERO_PAGE        0x84
#define STY_ZERO_PAGE_X      0x94
#define STY_ABSOLUTE         0x8C
#define TAX_IMPLIED          0xAA
#define TAY_IMPLIED          0xA8
#define TSX_IMPLIED          0xBA
#define TXA_IMPLIED          0x8A
#define TXS_IMPLIED          0x9A
#define TYA_IMPLIED          0x98
#define INVALID_INST NOP_IMPLIED

#endif // OPCODE_H
